// Scenario presets — coherent sets of assumptions applied via the preset bar.

import type { Preset } from '../types';

export const PRESETS: Preset[] = [
  {
    id: 'stress',
    label: 'Stress',
    description: 'Pessimistic: 0% real growth, no windfalls',
    tone: 'red',
    state: {
      growth: 0.02,
      equityPricePerShare: 0,
      equityYearsOut: 2,
      inheritanceK: 0,
      inheritanceAge: 60,
      alternateExitAge: 48,
      alternateExitK: 0,
      alternateDividendK: 0,
      alternateSalaryK: 0,
      alternateSalaryStartYears: 1,
      houseAge: 42,
      stopAge: 50,
      secondarySchoolPerKid: 30,
      partner2IncomeK: 0,
      partner2StartYears: 0,
      partner2DurationYears: 0,
    },
  },
  {
    id: 'central',
    label: 'Central',
    description: '3% real, equity at current price in 5 years, modest windfalls',
    tone: 'neutral',
    state: {
      growth: 0.03,
      equityPricePerShare: 1.56,
      equityYearsOut: 5,
      inheritanceK: 1000,
      inheritanceAge: 60,
      alternateExitAge: 48,
      alternateExitK: 200,
      alternateDividendK: 20,
      alternateSalaryK: 45,
      alternateSalaryStartYears: 1,
      houseAge: 46,
      stopAge: 50,
      secondarySchoolPerKid: 30,
      partner2IncomeK: 0,
      partner2StartYears: 0,
      partner2DurationYears: 0,
    },
  },
  {
    id: 'optimistic',
    label: 'Optimistic',
    description: '5% real (long-run historical), equity upside, partner 2 returns',
    tone: 'green',
    state: {
      growth: 0.05,
      equityPricePerShare: 2.60,
      equityYearsOut: 2,
      inheritanceK: 1000,
      inheritanceAge: 60,
      alternateExitAge: 48,
      alternateExitK: 750,
      alternateDividendK: 25,
      alternateSalaryK: 60,
      alternateSalaryStartYears: 1,
      houseAge: 45,
      stopAge: 50,
      secondarySchoolPerKid: 30,
      partner2IncomeK: 50,
      partner2StartYears: 2,
      partner2DurationYears: 8,
    },
  },
];

export const DEFAULT_PRESET_ID = 'central';
